version: '3'

services:
  db:
    image: postgres:12
    env_file: .env
  redis:
    image: "redis:alpine"
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c 'python manage.py runserver 0.0.0.0:8000; python manage.py migrate'
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - ./static:/static
    depends_on:
      - db
  celery:
    build: .
    command: celery -A config worker -l INFO
    env_file: .env
    depends_on:
      - db
      - redis

  react:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    stdin_open: true
    command: npm start
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend